app-description: Auth Microservice API for managing auth of CrediYa
app-title: Auth Management API
app-version: 1.0.0

server:
  port: "${APP_PORT:8080}"
spring:
  application:
    name: "MicroserviceAuth"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    database: "${DB_NAME:postgresql}"
    host: "${DB_HOST:localhost}"
    port: "${DB_PORT:5432}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASS:password}"
    schema: "${DB_SCHEMA:public}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/docs
  jwt:
    key: AuthorizationJWT
    scheme: bearer
    format: JWT
    name: Authorization
