##Spring Configuration
server:
  port: ${APP_PORT:8080}
spring:
  application:
    name: MicroserviceAuth
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
adapters:
  r2dbc:
    database: ${DB_NAME:postgresql}
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    schema: ${DB_SCHEMA:public}

